"""v3 migration

Revision ID: 2e01f58d11e1
Revises: a919c4f3ac69
Create Date: 2024-08-20 18:33:12.848323

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2e01f58d11e1'
down_revision = 'a919c4f3ac69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('access_token', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('refresh_token', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('access_token')
        batch_op.drop_column('device_id')

    # ### end Alembic commands ###
