"""v1.1

Revision ID: 73ad7256fb30
Revises: 80869c320a15
Create Date: 2024-09-13 18:29:12.826466

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '73ad7256fb30'
down_revision = '80869c320a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music_demo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('file_url', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('music_release',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('release_url', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('music_release')
    op.drop_table('music_demo')
    # ### end Alembic commands ###
